name: Get Workflow Details by Runner ID

on:
  workflow_dispatch:
    inputs:
      runner_id:
        description: 'Runner ID'
        required: true
        type: string

jobs:
  fetch-workflow-details:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name & Tag ID from Workflow Run
        id: get_branch_tag
        run: |
          # Fetch workflow run details
          WORKFLOW_DETAILS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID")

          # Extract branch name and tag details
          BRANCH_NAME=$(echo "$WORKFLOW_DETAILS" | jq -r '.head_branch')
          TAG_ID=$(echo "$WORKFLOW_DETAILS" | jq -r '.head_sha')

          echo "Branch Name: $BRANCH_NAME"
          echo "Tag ID: $TAG_ID"
          
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TAG_ID=$TAG_ID" >> $GITHUB_ENV

      - name: Display Extracted Details
        run: |
          echo "Branch Name: $BRANCH_NAME"
          echo "Tag ID: $TAG_ID"
