name: Run Jobs for Specific Branch

on:
  workflow_dispatch:
    inputs:
      branches:
        description: "Comma-separated list of branch names"
        required: true
        default: "main"

jobs:
  simple-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check out specific branch
        run: |
          echo "Checking out branch: ${{ github.event.inputs.branches }}"
          git fetch --all
          git checkout ${{ github.event.inputs.branches }}
