name: Download Workflow Logs

on:
  workflow_dispatch:
    inputs:
      workflow_id:
        description: "branch.yaml"
        required: true
        default: "branch.yaml"
      run_id:
        description: " "
        required: false
      token:
        description: "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"
        required: true

jobs:
  download-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        id: setup
        run: |
          mkdir -p logs

      - name: Fetch Workflow Run Logs
        id: fetch-logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WORKFLOW_ID=${{ inputs.workflow_id }}
          RUN_ID=${{ inputs.run_id }}
          TOKEN=${{ inputs.token }}

          # If RUN_ID is empty, fetch the latest run
          if [ -z "$RUN_ID" ]; then
            RUN_ID=$(curl -s \
              -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs?status=completed&per_page=1" \
              | jq -r '.workflow_runs[0].id')
          fi

          echo "Downloading logs for Run ID: $RUN_ID"

          # Download the logs
          curl -sL \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/logs" \
            -o logs/workflow_run_$RUN_ID.zip

      - name: Extract Logs
        if: success()
        run: |
          unzip logs/workflow_run_${{ steps.fetch-logs.outputs.RUN_ID }}.zip -d logs/

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflow-logs
          path: logs/
