name: Download Workflow Logs

on:
  workflow_dispatch:

jobs:
  download-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download logs of another workflow
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }} # Use the default token or your personal access token
          WORKFLOW_RUN_ID: 12579124363 # Replace with the actual workflow run ID
          REPO: pavvi17/helm-core-framework # Replace with your repository owner and name
        run: |
          # Fetch the logs
          echo "Downloading logs for workflow run ID: $WORKFLOW_RUN_ID"
          curl -L -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$REPO/actions/runs/$WORKFLOW_RUN_ID/logs" \
               -o logs.zip

          # Check if the download was successful
          if [ $? -ne 0 ]; then
            echo "Failed to download logs."
            exit 1
          fi

          # Unzip the logs
          echo "Unzipping logs..."
          unzip logs.zip -d logs

          # List the contents of the logs directory
          echo "Logs downloaded and unzipped:"
          ls logs
