name: Bump Minor Version on Feature Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump-minor:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # So we get full history and tags

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "latest=$latest_tag" >> "$GITHUB_OUTPUT"

      - name: Calculate next minor version
        id: bump_version
        run: |
          IFS='.' read -r major minor patch <<< "${{ steps.get_tag.outputs.latest }}"
          minor=$((minor + 1))
          new_version="$major.$minor.0"
          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Create and push new tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump_version.outputs.new_version }}
          git push origin ${{ steps.bump_version.outputs.new_version }}
