name: Get Workflow Details by Runner ID

on:
  workflow_dispatch:
    inputs:
      runner_id:
        description: 'Runner ID'
        required: true
        type: string

jobs:
  fetch-workflow-details:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Run ID from Runner ID
        id: get_run_id
        run: |
          RUNNER_ID="${{ github.event.inputs.runner_id }}"

          # Fetch recent jobs from all workflows
          JOBS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/${{ github.repository }}/actions/jobs")

          # Extract the workflow run ID using Runner ID
          RUN_ID=$(echo "$JOBS" | jq -r ".jobs[] | select(.runner_id == $RUNNER_ID) | .run_id" | head -n 1)

          if [[ -z "$RUN_ID" || "$RUN_ID" == "null" ]]; then
            echo "No workflow found for runner ID: $RUNNER_ID"
            exit 1
          fi

          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Found Workflow Run ID: $RUN_ID"

      - name: Get Branch Name & Tag ID from Workflow Run
        id: get_branch_tag
        run: |
          # Fetch workflow run details
          WORKFLOW_DETAILS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID")

          # Extract branch name and tag ID
          BRANCH_NAME=$(echo "$WORKFLOW_DETAILS" | jq -r '.head_branch')
          TAG_ID=$(echo "$WORKFLOW_DETAILS" | jq -r '.head_sha')

          if [[ "$BRANCH_NAME" == "null" || -z "$BRANCH_NAME" ]]; then
            echo "Error: Could not fetch branch name."
            exit 1
          fi

          echo "Branch Name: $BRANCH_NAME"
          echo "Tag ID: $TAG_ID"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TAG_ID=$TAG_ID" >> $GITHUB_ENV

      - name: Display Extracted Details
        run: |
          echo "Branch Name: $BRANCH_NAME"
          echo "Tag ID: $TAG_ID"
